export const HabitsData = [
  {
    id: 1,
    title: "Meditate",
    description: "Spend at least 5–10 minutes in mindful meditation every morning to stay calm and focused.",
    frequency: "Daily",
    streak: 0,
    icon: "🔥",
    category: "Health",
    completed: false,
  },
  {
    id: 2,
    title: "Read",
    description: "Read a minimum of 10 pages from a book or article to improve knowledge and focus.",
    frequency: "Daily",
    streak: 3,
    icon: "🔥",
    category: "Learning",
    completed: false,
  },
  {
    id: 3,
    title: "Workout",
    description: "Do 30 minutes of physical exercise such as running, gym, or yoga to stay active.",
    frequency: "Mon/Wed/Fri",
    streak: 5,
    icon: "🔥",
    category: "Fitness",
    completed: true,
  },
  {
    id: 4,
    title: "Drink Water",
    description: "Drink at least 8 glasses of water throughout the day to stay hydrated and healthy.",
    frequency: "Daily",
    streak: 7,
    icon: "🔥",
    category: "Health",
    completed: false,
  },
  {
    id: 5,
    title: "Journal Writing",
    description: "Write 3–5 sentences about your day, thoughts, or gratitude to clear your mind.",
    frequency: "Daily",
    streak: 2,
    icon: "🔥",
    category: "Mindfulness",
    completed: false,
  },
  {
    id: 6,
    title: "Practice Coding",
    description: "Spend at least 1 hour improving coding skills through practice or building projects.",
    frequency: "Daily",
    streak: 4,
    icon: "🔥",
    category: "Learning",
    completed: false,
  },
  {
    id: 7,
    title: "Stretching",
    description: "Perform 10–15 minutes of stretching to improve flexibility and prevent muscle tension.",
    frequency: "Daily",
    streak: 6,
    icon: "🔥",
    category: "Fitness",
    completed: false,
  },
  {
    id: 8,
    title: "Wake Up Early",
    description: "Wake up before 7 AM to start the day early and maximize productivity.",
    frequency: "Daily",
    streak: 8,
    icon: "🔥",
    category: "Lifestyle",
    completed: true,
  },
];
