export const HabitsData = [
  {
    id: 1,
    title: "Meditate",
    description: "Meditate 5–10 minutes each morning for focus.",
    frequency: "Daily",
    streak: 0,
    icon: "🔥",
    category: "Health",
    completed: false,
  },
  {
    id: 2,
    title: "Read",
    description: "Read 10+ pages to boost knowledge.",
    frequency: "Daily",
    streak: 3,
    icon: "🔥",
    category: "Learning",
    completed: false,
  },
  {
    id: 3,
    title: "Workout",
    description: "Exercise 30 minutes to stay fit.",
    frequency: "Mon/Wed/Fri",
    streak: 5,
    icon: "🔥",
    category: "Fitness",
    completed: true,
  },
  {
    id: 4,
    title: "Drink Water",
    description: "Drink 8 glasses of water daily.",
    frequency: "Daily",
    streak: 7,
    icon: "🔥",
    category: "Health",
    completed: false,
  },
  {
    id: 5,
    title: "Journal Writing",
    description: "Write 3–5 daily thoughts or notes.",
    frequency: "Daily",
    streak: 2,
    icon: "🔥",
    category: "Mindfulness",
    completed: false,
  },
  {
    id: 6,
    title: "Practice Coding",
    description: "Code for at least 1 hour daily.",
    frequency: "Daily",
    streak: 4,
    icon: "🔥",
    category: "Learning",
    completed: false,
  },
  {
    id: 7,
    title: "Stretching",
    description: "Stretch for 10–15 minutes daily.",
    frequency: "Daily",
    streak: 6,
    icon: "🔥",
    category: "Fitness",
    completed: false,
  },
  {
    id: 8,
    title: "Wake Up Early",
    description: "Wake before 7 AM for productivity.",
    frequency: "Daily",
    streak: 8,
    icon: "🔥",
    category: "Lifestyle",
    completed: true,
  },
];
