export const HabitsData = [
  {
    id: 1,
    title: "Meditate",
    description: "5 minutes of meditation every morning",
    frequency: "Daily",
    streak: 0,
    icon: "🔥",
    category: "Health",
    completed: false,
  },
  {
    id: 2,
    title: "Read",
    description: "Read 10 pages of a book",
    frequency: "Daily",
    streak: 3,
    icon: "📚",
    category: "Learning",
    completed: false,
  },
  {
    id: 3,
    title: "Workout",
    description: "30 minutes of exercise",
    frequency: "Mon/Wed/Fri",
    streak: 5,
    icon: "🏋️‍♂️",
    category: "Fitness",
    completed: true,
  },
  {
    id: 4,
    title: "Drink Water",
    description: "Drink at least 8 glasses of water",
    frequency: "Daily",
    streak: 7,
    icon: "💧",
    category: "Health",
    completed: false,
  },
];
